backend = "fastresize"
color_space = "lch"
palette = "dark"
#check_contrast = true
#saturation = 35
#alpha = 100

[templates]
hyprland.template = 'hyprland.conf'
hyprland.target = '~/.config/hypr/colors.conf'
waybar.template = 'waybar.css'
waybar.target = '~/.config/waybar/colors.css'
kitty.template = 'kitty.conf'
kitty.target = '~/.config/kitty/colors.conf'
